### ISSUE TITLE
EL Flat Panel failed to recognize change when Parked or Unparked

### ISSUE THREAD

**Issue by LauDeash** [RunTJoe/ELFlatPanel#2]
Hi @RunTJoe,

Huge thanks for sharing this solution flats solution.  A buddy of mine and I are right at the finish line building this, but we're having a small issue.  When we run the Indi flip_flat drive in Ekos I can manually unpark and park the cap but the buttons don't change to green respectively and the status light stays red.   It's all good if I'm going to babysit the rig that night, but it falls apart when I want to introduce automation, like the scheduler. Since it's not recognizing it's actually unparked when it is it causes it to abort the job.  I can't help but feel like it might be driver related and I've posted on the indilib forums, but I thought I'd reach out to you too.  See if you have any suggestions.  Thanks for any help you can offer and let me know what I can provide to help out.

**Comment by RunTJoe** [comment]
Hi @LauDeash ,
although I'm no expert on Indi software, let's try to find the issue. 

First, to ensure that I understand the problem (sorry - I'm no native speaker...): Basically the cap status (open or closed) is not displayed in your software? Is the light status (on or off) displayed correctly?

I have just checked the software with N.I.N.A. and it displays the correct cover state. So basically the firmware seems to work correctly, at least for N.I.N.A.

Then I have then tried to look at the indi driver source code (do you know whether [https://github.com/indilib/indi/blob/master/drivers/auxiliary/flip_flat.cpp](https://github.com/indilib/indi/blob/master/drivers/auxiliary/flip_flat.cpp) is the correct driver?) to see what the driver is expecting. 

Maybe I have an idea: There is a strange issue with the Alnitak protocol specification, you can find (at least) 2 different versions. The main difference is that the spec dated "1/11/09" states that the unused characters in the responses from the panel are "0" (the digit zero), but according to the spec dated "6/12/2017" these characters shall be "O" (the letter O). 

This seems to cause confusion; see a code snippet from N.I.N.A.:
`if (response.Substring(4, 3).Equals("OOO")) return true;`

and one from indi flip-flat driver:
`snprintf(expectedResponse, FLAT_RES, "*C%02d000", productID);
 if (strcmp(response, expectedResponse) == 0)`

My Arduino firmware accepts both characters as input, but outputs with "O"s (not 0s). Maybe you can replace the "O"s in line 115 to 117 of  the .ino file by "0"s, upload the new firmware to the Arduino and try again.

Please let me know whether this helps, I'll try to support finding the issue.

**Comment by LauDeash** [comment]
@RunTJoe,

Thanks for such a quick reply. Yes, I believe that is the right driver at least it’s the one I’ve been looking through. I’ll make those changes and let you know how it turns out.

**Comment by LauDeash** [comment]
@RunTJoe,

That was it!  Thanks so much for the help.

**Comment by RunTJoe** [comment]
> @RunTJoe,
> 
> That was it! Thanks so much for the help.

Thank you for reporting this problem. I have meanwhile opened an issue ticket for the INDI driver.
